version: "3.1"

services:
  php:
    container_name: mawaqit_php
    build: docker/php-fpm
    restart: always
    environment:
      APP_ENV: dev
      COMPOSER_HOME: /application/docker/data/composer
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php.ini.overrides:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro

  nginx:
    container_name: mawaqit_nginx
    image: nginx:alpine
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      #- /home/ibrahim/Tmp/mawaqit_upload:/application/web/upload
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10001:80

  db:
    container_name: mawaqit_mysql
    image: mysql:5.6
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mawaqit
      MYSQL_DATABASE: mawaqit
    ports:
      - 10002:3306

  elasticsearch:
    image: elasticsearch:6.8.6
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    volumes:
      - ./docker/data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  maildev:
    container_name: mawaqit_maildev
    restart: always
    image: djfarrelly/maildev:1.1.0
    ports:
      - 10003:80