version: "3.1"

services:
  mawaqit_php:
    container_name: mawaqit_php
    build: docker/php-fpm
    restart: always
    environment:
      APP_ENV: prod
      COMPOSER_HOME: /application/docker/data/composer
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php.ini.overrides:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro

  mawaqit_nginx:
    container_name: mawaqit_nginx
    image: nginx:alpine
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2053:443

  mawaqit_mysql:
    container_name: mawaqit_mysql
    image: mysql:5.6
    restart: always
    volumes:
      - /var/www/mawaqit/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:6.8.6
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    volumes:
      - ./docker/data/es:/usr/share/elasticsearch/data

  mawaqit_maildev:
    container_name: mawaqit_maildev
    restart: always
    image: djfarrelly/maildev:1.1.0
    ports:
      - 82:80