AppBundle\Entity\User:
    properties:
        plainPassword:
            - Regex: 
                pattern: '/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^\w\s]).{12,}$/'
                message: "form.registration.wrong_password_message"              
                groups: [appChangePassword]

AppBundle\Entity\Mosque:
    constraints:
        - AppBundle\Validator\Constraints\Mosque: ~
    properties:
        type:
            - NotBlank: ~
            - Choice :  {callback : "getTypes"}
        name:
            - NotBlank: ~
        email:
            - Email: ~
        site:
            - Url: ~
        address:
            - NotBlank:  {groups: [Mosque]}
        city:
            - NotBlank: ~
        zipcode:
            - NotBlank: ~
        country:
            - Country: ~

AppBundle\Entity\Message:
    constraints:
        - AppBundle\Validator\Constraints\Message: ~
            
AppBundle\Entity\Configuration:
    constraints:
        - AppBundle\Validator\Constraints\Configuration: ~
    properties:
        hadithLang:
            - Choice: {callback : "getHadithLangs"}
        asrMethod:
            - Choice: {callback : "getAsrMethodChoices"}
        highLatsMethod:
            - Choice: {callback : "getHighLatsChoices"}
        timeToDisplayMessage:
            - LessThanOrEqual: 60
            - GreaterThanOrEqual: 5


